# Welcome to the config of PrisonGangs!
# Appears when a player requests information about a gang Example would be 
# Leader • mydeblob - Online
seperator: •

# This is the max amount of characters allowed in a gang name
char-limit: 15

# If this is set to true there will be a scoreboard. Set to false to disable
scoreboard: true

# This is the format that the players gang name will appear in chat
# *********************For this to work you must add {GANG}*********************
# *********************in the chat format of your primary***********************
# *********************chat plugin! (Ex. EssentialsChat)************************
# %g% is replaced with the gang name
format: '&f[&8%g%&f]'

# These are words (or characters) that won't be allowed in gang names
blocked-names:
  - sucks
  - loser
  - dumb
  - $
  - {
  - }

# If this is set to true the plugin will auto update
auto-updater: true